name:                sam
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/sam#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - attoparsec-applicative
  - bytestring
  - base16-bytestring
  - data-default
  - containers
  - generic-deriving
  - lens
  - conduit
  - conduit-extra
#  - doctest

tests:
  sam-test:
    main:                Spec.hs
    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
    dependencies:
    - sam
## for doctest
#  test:
#    main: Main.hs
#    source-dirs: test

library:
  exposed-modules:
     - Bio.Sam.Sam
     - Bio.Sam.Cigar
     - Bio.Sam.IO
     - Bio.Sam.Parse
  source-dirs: lib
